### ISSUE TITLE
执行npm start报错了，后面都执行失败了问下

### ISSUE THREAD

**Issue by DavidWangWang** [su350380433/cocoapods-imy-bin-demo#6]
![83D7CDF2-B9BA-4538-9636-74ED82B8E211](https://user-images.githubusercontent.com/7679709/111427218-bfbdd080-8730-11eb-9dc7-e244fb117044.png)

执行npm start报错了，后面都执行失败了问下

**Comment by DavidWangWang** [comment]
解决了。mongo的问题

**Comment by fndppx** [comment]
> 解决了。mongo的问题

有遇到类似问题么？ pod bin auto error
<img width="654" alt="image" src="https://user-images.githubusercontent.com/7971897/162673653-d1340a5b-d386-4ca2-9053-a6baf675b514.png">
